CREATE TABLE public.users(
    id bigint generated by DEFAULT AS identity,
    user_name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    uid character varying NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);
--bun:split