CREATE TABLE public.sessions(
    id bigint generated by DEFAULT AS identity,
    user_id bigint NOT NULL,
    access_token character varying NOT NULL,
    refresh_token character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_sessions_users FOREIGN KEY (user_id) REFERENCES public.users(id)
)
--bun:split
