SET statement_timeout = 0;
CREATE TABLE tags(
    id bigint generated by DEFAULT AS identity,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
)
--bun:split
CREATE TABLE lists(
    id bigint generated by DEFAULT AS identity,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
)
--bun:split
CREATE TYPE todo_status AS ENUM ('todo', 'doing', 'done');
--bun:split
CREATE TABLE todos(
    id bigint generated by DEFAULT AS identity,
    title character varying NOT NULL,
    description character varying NOT NULL,
    status todo_status NOT NULL DEFAULT 'todo',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    list_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (list_id) REFERENCES public.lists(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES public.users(id)
)
--bun:split
CREATE TABLE todo_tags(
    id bigint generated by DEFAULT AS identity,
    todo_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (todo_id) REFERENCES public.todos(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE
)
--bun:split